window.PRODUCTS = [
  { id: 1, name: 'Engrenagem Cilíndrica Módulo 2', category: 'Engrenagens', price: 189.9, old: 229.9, rating: 4.9, reviews: 82, sku: 'ENG-M2-20', badge: 'Mais vendida', stock:12, description: 'Engrenagem cilíndrica para transmissão mecânica em aplicações industriais.', specs: { 'Categoria': 'Engrenagem cilíndrica', 'Módulo': '2', 'Aplicação': 'Transmissão mecânica', 'SKU': 'ENG-M2-20' } },
  { id: 2, name: 'Engrenagem Helicoidal Módulo 2', category: 'Engrenagens', price: 249.9, old: 289.9, rating: 4.8, reviews: 57, sku: 'HEL-M2-20', badge: 'Oferta', stock:8, description: 'Engrenagem helicoidal para transmissão suave e operação contínua.', specs: { 'Categoria': 'Engrenagem helicoidal', 'Módulo': '2', 'Aplicação': 'Transmissão mecânica', 'SKU': 'HEL-M2-20' } },
  { id: 3, name: 'Pinhão para Corrente 08B', category: 'Pinhões', price: 119.9, old: null, rating: 4.8, reviews: 44, sku: 'PIN-08B-15', badge: null, stock:24, description: 'Pinhão para corrente de rolos para sistemas de transmissão industrial.', specs: { 'Categoria': 'Pinhão', 'Norma': '08B', 'Aplicação': 'Correntes de transmissão', 'SKU': 'PIN-08B-15' } },
  { id: 4, name: 'Pinhão para Corrente 10B', category: 'Pinhões', price: 149.9, old: 179.9, rating: 4.7, reviews: 36, sku: 'PIN-10B-15', badge: 'Oferta', stock:0, description: 'Pinhão para corrente de rolos para acionamentos industriais.', specs: { 'Categoria': 'Pinhão', 'Norma': '10B', 'Aplicação': 'Correntes de transmissão', 'SKU': 'PIN-10B-15' } },
  { id: 5, name: 'Polia em V Perfil A', category: 'Polias', price: 99.9, old: null, rating: 4.6, reviews: 31, sku: 'POL-A-02', badge: null, stock:16, description: 'Polia em V para transmissão por correias em máquinas e equipamentos.', specs: { 'Categoria': 'Polia em V', 'Perfil': 'A', 'Aplicação': 'Correias industriais', 'SKU': 'POL-A-02' } },
  { id: 6, name: 'Polia em V Perfil B', category: 'Polias', price: 159.9, old: 189.9, rating: 4.8, reviews: 28, sku: 'POL-B-03', badge: 'Oferta', stock:6, description: 'Polia em V perfil B para conjuntos de transmissão e acionamento.', specs: { 'Categoria': 'Polia em V', 'Perfil': 'B', 'Aplicação': 'Correias industriais', 'SKU': 'POL-B-03' } },
  { id: 7, name: 'Acoplamento Elástico 19', category: 'Acoplamentos', price: 329.9, old: 379.9, rating: 4.9, reviews: 22, sku: 'ACP-19-01', badge: 'Novo', stock:9, description: 'Acoplamento elástico para absorção de vibrações e desalinhamentos.', specs: { 'Categoria': 'Acoplamento elástico', 'Tamanho': '19', 'Aplicação': 'Eixos e acionamentos', 'SKU': 'ACP-19-01' } },
  { id: 8, name: 'Acoplamento de Grade 1020', category: 'Acoplamentos', price: 549.9, old: 619.9, rating: 4.7, reviews: 17, sku: 'ACP-G-1020', badge: null, stock:3, description: 'Acoplamento de grade para transmissão de torque em aplicações industriais.', specs: { 'Categoria': 'Acoplamento de grade', 'Tamanho': '1020', 'Aplicação': 'Transmissão de torque', 'SKU': 'ACP-G-1020' } },
  { id: 9, name: 'Corrente de Transmissão 08B', category: 'Correntes', price: 169.9, old: null, rating: 4.8, reviews: 64, sku: 'COR-08B-05', badge: 'Mais vendida', stock:32, description: 'Corrente de transmissão de rolos para acionamentos industriais.', specs: { 'Categoria': 'Corrente de rolos', 'Norma': '08B', 'Aplicação': 'Transmissão industrial', 'SKU': 'COR-08B-05' } },
  { id: 10, name: 'Corrente de Transmissão 10B', category: 'Correntes', price: 219.9, old: 249.9, rating: 4.7, reviews: 39, sku: 'COR-10B-05', badge: 'Oferta', stock:10, description: 'Corrente de transmissão de rolos para equipamentos e máquinas industriais.', specs: { 'Categoria': 'Corrente de rolos', 'Norma': '10B', 'Aplicação': 'Transmissão industrial', 'SKU': 'COR-10B-05' } },
  { id: 11, name: 'Coroa de Corrente 08B', category: 'Coroas', price: 139.9, old: null, rating: 4.6, reviews: 21, sku: 'COROA-08B-15', badge: null, stock:18, description: 'Coroa para corrente de rolos, indicada para sistemas de transmissão.', specs: { 'Categoria': 'Coroa', 'Norma': '08B', 'Aplicação': 'Correntes de transmissão', 'SKU': 'COROA-08B-15' } },
  { id: 12, name: 'Coroa de Corrente 10B', category: 'Coroas', price: 189.9, old: 219.9, rating: 4.8, reviews: 25, sku: 'COROA-10B-15', badge: 'Oferta', stock:4, description: 'Coroa para corrente de rolos em conjuntos de transmissão mecânica.', specs: { 'Categoria': 'Coroa', 'Norma': '10B', 'Aplicação': 'Correntes de transmissão', 'SKU': 'COROA-10B-15' } }
];
