const products=[
{id:1,name:'Engrenagem Cilíndrica Módulo 2',category:'Engrenagens',price:189.9,old:229.9,rating:4.9,reviews:82,sku:'ENG-M2-20',badge:'Mais vendida'},
{id:2,name:'Engrenagem Helicoidal Módulo 2',category:'Engrenagens',price:249.9,old:289.9,rating:4.8,reviews:57,sku:'HEL-M2-20',badge:'Oferta'},
{id:3,name:'Pinhão para Corrente 08B',category:'Pinhões',price:119.9,old:null,rating:4.8,reviews:44,sku:'PIN-08B-15',badge:null},
{id:4,name:'Pinhão para Corrente 10B',category:'Pinhões',price:149.9,old:179.9,rating:4.7,reviews:36,sku:'PIN-10B-15',badge:'Oferta'},
{id:5,name:'Polia em V Perfil A',category:'Polias',price:99.9,old:null,rating:4.6,reviews:31,sku:'POL-A-02',badge:null},
{id:6,name:'Polia em V Perfil B',category:'Polias',price:159.9,old:189.9,rating:4.8,reviews:28,sku:'POL-B-03',badge:'Oferta'},
{id:7,name:'Acoplamento Elástico 19',category:'Acoplamentos',price:329.9,old:379.9,rating:4.9,reviews:22,sku:'ACP-19-01',badge:'Novo'},
{id:8,name:'Acoplamento de Grade 1020',category:'Acoplamentos',price:549.9,old:619.9,rating:4.7,reviews:17,sku:'ACP-G-1020',badge:null},
{id:9,name:'Corrente de Transmissão 08B',category:'Correntes',price:169.9,old:null,rating:4.8,reviews:64,sku:'COR-08B-05',badge:'Mais vendida'},
{id:10,name:'Corrente de Transmissão 10B',category:'Correntes',price:219.9,old:249.9,rating:4.7,reviews:39,sku:'COR-10B-05',badge:'Oferta'},
{id:11,name:'Coroa de Corrente 08B',category:'Coroas',price:139.9,old:null,rating:4.6,reviews:21,sku:'COROA-08B-15',badge:null},
{id:12,name:'Coroa de Corrente 10B',category:'Coroas',price:189.9,old:219.9,rating:4.8,reviews:25,sku:'COROA-10B-15',badge:'Oferta'}
];
const categories=['Todos',...new Set(products.map(p=>p.category))];
let state={cat:'Todos',search:'',sort:'featured',cart:JSON.parse(localStorage.getItem('engrenagens-cart')||'[]')};
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const grid=document.getElementById('grid'),pills=document.getElementById('pills'),quoteProduct=document.getElementById('quoteProduct');
categories.forEach(c=>{const b=document.createElement('button');b.className='pill'+(c==='Todos'?' active':'');b.textContent=c;b.onclick=()=>{state.cat=c;document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};pills.appendChild(b)});
products.forEach(p=>{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;quoteProduct.appendChild(o)});
function filtered(){let a=products.filter(p=>(state.cat==='Todos'||p.category===state.cat)&&`${p.name} ${p.category} ${p.sku}`.toLowerCase().includes(state.search.toLowerCase()));if(state.sort==='priceAsc')a.sort((x,y)=>x.price-y.price);if(state.sort==='priceDesc')a.sort((x,y)=>y.price-x.price);if(state.sort==='rating')a.sort((x,y)=>y.rating-x.rating);return a}
function render(){grid.innerHTML=filtered().map(p=>`<article class="product"><div class="thumb">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="wish" onclick="toggleWish(this)" aria-label="Favoritar ${p.name}">♡</button><div class="thumbArt"></div></div><div class="info"><div class="category">${p.category}</div><div class="name">${p.name}</div><div class="sku">SKU ${p.sku}</div><div class="rating">★ <b>${p.rating}</b> · ${p.reviews} avaliações</div><div class="price"><strong>${brl(p.price)}</strong>${p.old?`<span class="old">${brl(p.old)}</span>`:''}</div><button class="add" onclick="addToCart(${p.id})">Adicionar ao pedido</button></div></article>`).join('')||'<div class="empty" style="grid-column:1/-1">Nenhum produto encontrado. Tente outro termo.</div>'}
function toggleWish(btn){btn.classList.toggle('active');btn.textContent=btn.classList.contains('active')?'♥':'♡'}
function save(){localStorage.setItem('engrenagens-cart',JSON.stringify(state.cart));updateCart()}
function addToCart(id){let i=state.cart.find(x=>x.id===id);if(i)i.qty++;else state.cart.push({id,qty:1});save();openCart()}
function updateCart(){document.getElementById('cartCount').textContent=state.cart.reduce((s,i)=>s+i.qty,0);const body=document.getElementById('cartBody');if(!state.cart.length){body.innerHTML='<div class="empty">Seu pedido está vazio.<br>Adicione peças do catálogo.</div>'}else{body.innerHTML=state.cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cartItem"><div class="cartThumb">⚙️</div><div><b>${p.name}</b><div style="font-size:11px;color:#777">SKU ${p.sku}</div><div style="font-size:12px;color:#777">${brl(p.price)} cada</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button><span class="remove" onclick="removeItem(${p.id})">remover</span></div></div><b>${brl(p.price*i.qty)}</b></div>`}).join('')};document.getElementById('cartTotal').textContent=brl(state.cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0))}
function changeQty(id,d){const i=state.cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);save()}function removeItem(id){state.cart=state.cart.filter(x=>x.id!==id);save()}
function openCart(){document.getElementById('drawer').classList.add('open');document.getElementById('overlay').classList.add('open')}function closeCart(){document.getElementById('drawer').classList.remove('open');document.getElementById('overlay').classList.remove('open')}
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('search').addEventListener('input',e=>{state.search=e.target.value;render()});document.getElementById('sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.getElementById('searchFocus').onclick=()=>{document.getElementById('search').focus();document.getElementById('catalogo').scrollIntoView({behavior:'smooth'})};
const modal=document.getElementById('modal');document.getElementById('checkoutBtn').onclick=()=>{if(!state.cart.length)return alert('Seu pedido está vazio.');modal.classList.add('open')};document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');document.getElementById('cancelCheckout').onclick=()=>modal.classList.remove('open');document.getElementById('checkoutForm').onsubmit=e=>{e.preventDefault();modal.classList.remove('open');state.cart=[];save();closeCart();alert('Pedido demonstrativo confirmado. Para vendas reais, conecte o gateway de pagamento e o backend de pedidos.')};document.getElementById('quoteForm').onsubmit=e=>{e.preventDefault();alert('Solicitação de orçamento registrada no modo demonstrativo. Conecte este formulário ao e-mail, CRM ou WhatsApp da empresa.')};
render();updateCart();
