const products = window.PRODUCTS;
const categories=['Todos',...new Set(products.map(p=>p.category))];
let state={cat:'Todos',search:'',sort:'featured',cart:JSON.parse(localStorage.getItem('engrenagens-cart')||'[]')};
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const grid=document.getElementById('grid'),pills=document.getElementById('pills'),quoteProduct=document.getElementById('quoteProduct');
categories.forEach(c=>{const b=document.createElement('button');b.className='pill'+(c==='Todos'?' active':'');b.textContent=c;b.onclick=()=>{state.cat=c;document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};pills.appendChild(b)});
products.forEach(p=>{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;quoteProduct.appendChild(o)});
function filtered(){let a=products.filter(p=>(state.cat==='Todos'||p.category===state.cat)&&`${p.name} ${p.category} ${p.sku}`.toLowerCase().includes(state.search.toLowerCase()));if(state.sort==='priceAsc')a.sort((x,y)=>x.price-y.price);if(state.sort==='priceDesc')a.sort((x,y)=>y.price-x.price);if(state.sort==='rating')a.sort((x,y)=>y.rating-x.rating);return a}
function render(){grid.innerHTML=filtered().map(p=>`<article class="product" onclick="openProduct(${p.id})"><div class="thumb">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="wish" onclick="event.stopPropagation();toggleWish(this)" aria-label="Favoritar ${p.name}">♡</button><div class="thumbArt"></div></div><div class="info"><div class="category">${p.category}</div><div class="name">${p.name}</div><div class="sku">SKU ${p.sku}</div><div class="rating">★ <b>${p.rating}</b> · ${p.reviews} avaliações</div><div class="price"><strong>${brl(p.price)}</strong>${p.old?`<span class="old">${brl(p.old)}</span>`:''}</div><button class="add" onclick="event.stopPropagation();addToCart(${p.id})">Adicionar ao pedido</button></div></article>`).join('')||'<div class="empty" style="grid-column:1/-1">Nenhum produto encontrado. Tente outro termo.</div>'}
function toggleWish(btn){btn.classList.toggle('active');btn.textContent=btn.classList.contains('active')?'♥':'♡'}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById('detailCategory').textContent=p.category;document.getElementById('detailName').textContent=p.name;document.getElementById('detailSku').textContent='SKU '+p.sku;document.getElementById('detailRating').innerHTML='★ <b>'+p.rating+'</b> · '+p.reviews+' avaliações';document.getElementById('detailDescription').textContent=p.description||'Componente para aplicações industriais e transmissão mecânica.';document.getElementById('detailPrice').textContent=brl(p.price);document.getElementById('detailOld').textContent=p.old?brl(p.old):'';document.getElementById('detailSpecs').innerHTML=Object.entries(p.specs||{}).map(([k,v])=>`<div class="specItem"><small>${k}</small><b>${v}</b></div>`).join('');document.getElementById('detailAdd').onclick=()=>{addToCart(p.id);closeProduct()};document.getElementById('detailQuote').onclick=()=>{closeProduct();document.getElementById('quoteProduct').value=p.name;document.getElementById('orcamento').scrollIntoView({behavior:'smooth'})};document.getElementById('productModal').classList.add('open')}
function closeProduct(){document.getElementById('productModal').classList.remove('open')}
function save(){localStorage.setItem('engrenagens-cart',JSON.stringify(state.cart));updateCart()}
function addToCart(id){let i=state.cart.find(x=>x.id===id);if(i)i.qty++;else state.cart.push({id,qty:1});save();openCart()}
function updateCart(){document.getElementById('cartCount').textContent=state.cart.reduce((s,i)=>s+i.qty,0);const body=document.getElementById('cartBody');if(!state.cart.length){body.innerHTML='<div class="empty">Seu pedido está vazio.<br>Adicione peças do catálogo.</div>'}else{body.innerHTML=state.cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cartItem"><div class="cartThumb">⚙️</div><div><b>${p.name}</b><div style="font-size:11px;color:#777">SKU ${p.sku}</div><div style="font-size:12px;color:#777">${brl(p.price)} cada</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button><span class="remove" onclick="removeItem(${p.id})">remover</span></div></div><b>${brl(p.price*i.qty)}</b></div>`}).join('')};document.getElementById('cartTotal').textContent=brl(state.cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0))}
function changeQty(id,d){const i=state.cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);save()}function removeItem(id){state.cart=state.cart.filter(x=>x.id!==id);save()}
function openCart(){document.getElementById('drawer').classList.add('open');document.getElementById('overlay').classList.add('open')}function closeCart(){document.getElementById('drawer').classList.remove('open');document.getElementById('overlay').classList.remove('open')}
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeProductModal').onclick=closeProduct;document.getElementById('productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProduct();modal.classList.remove('open');closeCart()}});document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('search').addEventListener('input',e=>{state.search=e.target.value;render()});document.getElementById('sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.getElementById('searchFocus').onclick=()=>{document.getElementById('search').focus();document.getElementById('catalogo').scrollIntoView({behavior:'smooth'})};
const modal=document.getElementById('modal');document.getElementById('checkoutBtn').onclick=()=>{if(!state.cart.length)return alert('Seu pedido está vazio.');modal.classList.add('open')};document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');document.getElementById('cancelCheckout').onclick=()=>modal.classList.remove('open');document.getElementById('checkoutForm').onsubmit=e=>{e.preventDefault();modal.classList.remove('open');state.cart=[];save();closeCart();alert('Pedido demonstrativo confirmado. Para vendas reais, conecte o gateway de pagamento e o backend de pedidos.')};document.getElementById('quoteForm').onsubmit=e=>{e.preventDefault();alert('Solicitação de orçamento registrada no modo demonstrativo. Conecte este formulário ao e-mail, CRM ou WhatsApp da empresa.')};
render();updateCart();
